version: '3'
services:
  rabbitMq:
    image: rabbitmq:3-management
    container_name: rabbitMq_container
    ports:
      - "5672:5672"
      - "15672:15672"

  facade:
    image: facade
    container_name: facade
    ports:
      - "8080:8080"

  account-mgmt-service:
    image: account-mgmt
    container_name: account-mgmt

  report-mgmt-service:
    image: report-mgmt
    container_name: report-mgmt

  token-mgmt-service:
    image: token-mgmt
    container_name: token-mgmt

  payment-mgmt-service:
    image: payment-mgmt
    container_name: payment-mgmt